
-- ==============================================================================
-- 1. Tablas Independientes (No tienen llaves foráneas)
-- ==============================================================================

CREATE TABLE area (
    id_area BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL, -- Ej: Marketing, oGV
    siglas VARCHAR(15)
);
ALTER TABLE area ENABLE ROW LEVEL SECURITY;

CREATE TABLE cargo (
    id_cargo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cargo VARCHAR(100) NOT NULL, -- Ej: LCP, LCVP, TL, Member
    nivel_jerarquia INT NOT NULL -- Define el orden en el Directorio
);
ALTER TABLE cargo ENABLE ROW LEVEL SECURITY;

CREATE TABLE oportunidad (
    id_oportunidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    imagen_url TEXT,
    categoria VARCHAR(100) -- Ej: IXP, Liderazgo Local, Liderazgo Nacional
);
ALTER TABLE oportunidad ENABLE ROW LEVEL SECURITY;

CREATE TABLE logro_gamificacion (
    id_logro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL, -- Ej: Primeros pasos, Meta cumplida, On fire
    descripcion_requisito TEXT, -- Ej: Asistir al primer evento de interacción
    icono_url TEXT
);
ALTER TABLE logro_gamificacion ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 2. Tabla Principal de Usuarios (Depende de AREA y CARGO)
-- ==============================================================================

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_auth UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Enlace con Supabase Auth
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    correo VARCHAR(150) UNIQUE NOT NULL,
    telefono VARCHAR(30),
    fecha_nacimiento DATE, -- Para módulo de cumpleaños
    fecha_ingreso DATE, -- Para calcular Antigüedad (Ej: 4m)
    universidad VARCHAR(150), -- Ej: USAT
    carrera VARCHAR(150), -- Ej: Administración de empresas
    ciclo_academico VARCHAR(50), -- Ej: IX Ciclo
    linkedin_url TEXT,
    instagram_url TEXT,
    foto_perfil_url TEXT,
    es_miembro_activo BOOLEAN DEFAULT TRUE, -- Badge de 'Member Activo'
    
    -- Relaciones
    id_area BIGINT REFERENCES area(id_area) ON DELETE SET NULL,
    id_cargo BIGINT REFERENCES cargo(id_cargo) ON DELETE SET NULL,
    id_lider_directo BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL -- Autoreferencia
);
ALTER TABLE usuario ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 3. Tablas Dependientes
-- ==============================================================================

CREATE TABLE evento (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL, -- Ej: LCM, Reunión de Área
    fecha_hora_inicio TIMESTAMPTZ NOT NULL,
    fecha_hora_fin TIMESTAMPTZ,
    lugar VARCHAR(200), -- Ej: Oficina 3B, Facultad de Negocios
    modalidad VARCHAR(50), -- Ej: Virtual, Presencial
    tipo_evento VARCHAR(100), -- Ej: LEC, ITM, TEAM DAY
    id_area BIGINT REFERENCES area(id_area) ON DELETE CASCADE -- Opcional, si el evento es de un área específica
);
ALTER TABLE evento ENABLE ROW LEVEL SECURITY;

CREATE TABLE asistencia (
    id_asistencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_evento BIGINT NOT NULL REFERENCES evento(id_evento) ON DELETE CASCADE,
    estado VARCHAR(50), -- Ej: Registrada, Confirmada, Ausente
    fecha_registro TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE asistencia ENABLE ROW LEVEL SECURITY;

CREATE TABLE tarea (
    id_tarea BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_asignado BIGINT REFERENCES usuario(id_usuario) ON DELETE SET NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(50) DEFAULT 'Pendiente', -- Ej: Pendiente, En progreso, Completada
    fecha_limite TIMESTAMPTZ
);
ALTER TABLE tarea ENABLE ROW LEVEL SECURITY;

CREATE TABLE meta_kpi (
    id_meta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL, -- Ej: %Membresía Activa, # APDs, Meta Financiera
    valor_actual NUMERIC(10, 2) DEFAULT 0,
    valor_objetivo NUMERIC(10, 2) NOT NULL,
    id_area BIGINT REFERENCES area(id_area) ON DELETE CASCADE
);
ALTER TABLE meta_kpi ENABLE ROW LEVEL SECURITY;

CREATE TABLE usuario_logro (
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    id_logro BIGINT NOT NULL REFERENCES logro_gamificacion(id_logro) ON DELETE CASCADE,
    fecha_obtencion TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id_usuario, id_logro) -- Llave primaria compuesta
);
ALTER TABLE usuario_logro ENABLE ROW LEVEL SECURITY;

CREATE TABLE progreso_semanal (
    id_progreso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    semana INT NOT NULL,
    porcentaje INT CHECK (porcentaje >= 0 AND porcentaje <= 100) -- Ej: 90% de performance
);
ALTER TABLE progreso_semanal ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 4. Plantillas y Detalles de Tareas
-- ==============================================================================

CREATE TABLE tarea_plantilla (
    id_plantilla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,
    id_area BIGINT REFERENCES area(id_area) ON DELETE CASCADE,
    id_cargo BIGINT REFERENCES cargo(id_cargo) ON DELETE CASCADE,
    es_obligatoria BOOLEAN DEFAULT TRUE
);
ALTER TABLE tarea_plantilla ENABLE ROW LEVEL SECURITY;

ALTER TABLE tarea
ADD COLUMN id_plantilla BIGINT REFERENCES tarea_plantilla(id_plantilla);

CREATE TABLE tarea_detalle (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tarea BIGINT REFERENCES tarea(id_tarea) ON DELETE CASCADE,
    descripcion TEXT,
    completado BOOLEAN DEFAULT FALSE
);
ALTER TABLE tarea_detalle ENABLE ROW LEVEL SECURITY;
-- ==============================================================================
-- 1. FUNCIÓN Y TRIGGER PARA SUPABASE AUTH
-- Esto inserta automáticamente un registro en tu tabla 'usuario' 
-- cada vez que alguien se registra en el sistema de autenticación de Supabase.
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.usuario (id_auth, correo, nombres, apellidos, es_miembro_activo)
  VALUES (
    new.id, 
    new.email, 
    -- Supabase permite pasar metadata al registrarse (ej. nombres y apellidos). 
    -- Usamos COALESCE por si se registran sin enviar esos datos, para que no falle el NOT NULL.
    COALESCE(new.raw_user_meta_data->>'nombres', 'Usuario Nuevo'), 
    COALESCE(new.raw_user_meta_data->>'apellidos', 'Por actualizar'),
    TRUE
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Eliminamos el trigger si existe para evitar errores al re-ejecutar
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ==============================================================================
-- 2. POLÍTICAS DE SEGURIDAD RLS (Row Level Security)
-- ==============================================================================

-- ---------------------------------------------------------
-- POLÍTICAS GENERALES (Catálogos y vistas públicas para el comité)
-- Permite que cualquier miembro logueado pueda VER la información base.
-- ---------------------------------------------------------
CREATE POLICY "Lectura pública de áreas" ON area FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura pública de cargos" ON cargo FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura pública de oportunidades" ON oportunidad FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura pública de logros" ON logro_gamificacion FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura pública de eventos" ON evento FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura pública de metas KPI" ON meta_kpi FOR SELECT TO authenticated USING (true);
CREATE POLICY "Lectura pública de plantillas" ON tarea_plantilla FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------
-- POLÍTICAS DE USUARIO (Perfiles)
-- Todos pueden ver a los demás miembros del comité, pero solo uno mismo puede editar su perfil.
-- ---------------------------------------------------------
CREATE POLICY "Ver perfiles del comité" ON usuario FOR SELECT TO authenticated USING (true);

CREATE POLICY "Actualizar perfil propio" ON usuario FOR UPDATE TO authenticated 
USING (id_auth = auth.uid()) 
WITH CHECK (id_auth = auth.uid());

-- ---------------------------------------------------------
-- POLÍTICAS DE TAREAS Y ASISTENCIA
-- ---------------------------------------------------------
-- Todos pueden ver las tareas y asistencias (para transparencia en el equipo)
CREATE POLICY "Ver todas las tareas" ON tarea FOR SELECT TO authenticated USING (true);
CREATE POLICY "Ver todas las asistencias" ON asistencia FOR SELECT TO authenticated USING (true);
CREATE POLICY "Ver detalles de tareas" ON tarea_detalle FOR SELECT TO authenticated USING (true);

-- (Opcional) Solo el usuario asignado puede actualizar el estado de su tarea
CREATE POLICY "Actualizar tareas propias" ON tarea FOR UPDATE TO authenticated 
USING (
  id_usuario_asignado = (SELECT id_usuario FROM usuario WHERE id_auth = auth.uid())
);

-- ---------------------------------------------------------
-- PERMISOS DE INSERCIÓN/CREACIÓN (Para desarrollo)
-- *Nota: En producción podrías restringir esto solo a LCP/LCVP.
-- Por ahora, permitiremos que usuarios autenticados inserten datos básicos.
-- ---------------------------------------------------------
CREATE POLICY "Crear tareas" ON tarea FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Marcar asistencia" ON asistencia FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Crear eventos" ON evento FOR INSERT TO authenticated WITH CHECK (true);